<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MeshStatsViewer</AssemblyName>
    <AssemblyTitle>Mesh Stats Viewer</AssemblyTitle>
    <Version>1.0.0</Version>
    <!--The file where mod information which is required for publishing mod on PDX mods are stored-->
    <PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
  </PropertyGroup>
  <!--Imports must be after PropertyGroup block-->
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />
  <Import Project="$(CS2_STARQ_SHARED_PATH)\StarQ.Shared.projitems" Label="Shared" />
  <Import Project="$(CS2_STARQ_SHARED_PATH)\StarQ.Shared.props" />
  <Import Project="$(CS2_STARQ_SHARED_PATH)\StarQ.Shared.targets" />
</Project>
