<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MeshStatsViewer</AssemblyName>
    <AssemblyTitle>Mesh Stats Viewer</AssemblyTitle>
    <Version>0.9.3</Version>
    <!--The file where mod information which is required for publishing mod on PDX mods are stored-->
    <PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
  </PropertyGroup>
  <!--Imports must be after PropertyGroup block-->
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />
  <Import Project="..\..\ModsPersonal\StarQ.Shared\StarQ.Shared.projitems" Label="Shared" />
  <Import Project="..\..\ModsPersonal\StarQ.Shared\StarQ.Shared.props" />
  <Import Project="..\..\ModsPersonal\StarQ.Shared\StarQ.Shared.targets" />
</Project>
